config/routes.rb
Rails.application.routes.draw do
  get 'welcome', to: 'login#show', as: 'welcome'

  match 'sessions/create', to: 'sessions#create', via: :post, as: 'login'
  match 'sessions/destroy', to: 'sessions#destroy', via: [:delete, :get], as: 'logout'

  # users shouldn't be accessible
  # get 'users', to: 'users#index', as: 'users'

  get 'users/new', to: 'users#new', as: 'register'
  post 'users', to: 'users#create', as: 'user'

  get 'users/:id/edit', to: 'users#edit' , as: 'edit_profile'
  put 'users/:id', to: 'users#update', as: 'update_profile'

  get 'users/forgotten'
  post 'users/send_forgotten'

  get 'users/:id', to: 'users#show', as: 'profile'

  delete 'users/:id/destroy', to: 'users#destroy', as: 'delete_profile'

  resources :channels

  root :to => redirect('/welcome')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  before_save :encrypt_password

  validates :email, {presence: true, uniqueness: true}
  validates :username, {presence: true, uniqueness: true}
  validates :password, confirmation: true, if: :password_required?

  def password_required?
    self.new_record? || !self.password.blank?
  end

  def self.encrypt(pass, salt)
    Digest::SHA1.hexdigest(pass + salt)
  end

  def encrypt_password
    return if password.blank?
    if new_record?
      self.salt = SecureRandom.hex(16)
    end
    self.password_hash = User.encrypt self.password, self.salt
  end

  def self.authenticate(username, pass)
    user = User.where(username: username).first
    user && user.authenticated?(pass) ? user : nil
  end

  def authenticated?(pass)
    self.password_hash == User.encrypt(pass, self.salt)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: [:show, :edit, :update, :destroy]

  # GET /channels
  # GET /channels.json
  def index
    @channels = Channel.all
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url, notice: 'Channel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def channel_params
      params.require(:channel).permit(:name)
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def show
    if session[:user]
      # todo: change redirect
      redirect_to channels_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.authenticate params[:username], params[:password]
    if @user
      flash[:notice] = "Logged in successfully"
      session[:user] = @user.id
      # todo: change redirect
      redirect_to channels_path
    else
      flash[:notice] = "Invalid username or password"
      redirect_to welcome_path
    end
  end

  def destroy
    session[:user] = nil
    # reset_session seems to destroy all cookies, logging me out from facebok, gmail, basicly from everything
    # so I just made it nil
    flash[:notice] = "Logged out successfully"
    redirect_to welcome_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_auth, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    unless @auth_user == @user
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
    end
  end

  # GET /users/new
  def new
  end

  # GET /users/1/edit
  def edit
  end

  # GET /users/forgotten
  def forgotten
  end

  # POST /users/recover
  def recover
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.img = "/img/user.png"

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def check_auth
    unless session[:user]
      redirect_to welcome_path
    end
    @auth_user = User.find_by_id(session[:user])
    # If can't find the logged in user, destroy session
    unless @auth_user
      redirect_to logout_path
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find_by_id(params[:id])
    if @user == nil
      render(:file => File.join(Rails.root, 'public/404.html'), :status => 404, :layout => false)
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :username, :img, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/channels/_form.html.erb
<%= form_with(model: channel, local: true) do |form| %>
  <% if channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
      <% channel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Editing Channel</h1>

<%= render 'form', channel: @channel %>

<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

app/views/channels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Channels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @channels.each do |channel| %>
      <tr>
        <td><%= channel.name %></td>
        <td><%= link_to 'Show', channel %></td>
        <td><%= link_to 'Edit', edit_channel_path(channel) %></td>
        <td><%= link_to 'Destroy', channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Channel', new_channel_path %>

app/views/channels/new.html.erb
<h1>New Channel</h1>

<%= render 'form', channel: @channel %>

<%= link_to 'Back', channels_path %>

app/views/channels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @channel.name %>
</p>

<%= link_to 'Edit', edit_channel_path(@channel) %> |
<%= link_to 'Back', channels_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyMessenger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- Webfonts-->
    <link href="https://fonts.googleapis.com/css?family=Condiment:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">

    <link rel="stylesheet" href="./css/bootstrap.min.css"/>
    <script src="./js/jquery.min.js"></script>
    <script src="./js/bootstrap.min.js"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <% if content_for?(:head) %>
      <%= yield(:head) %>
    <% end %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/login/show.html.erb
<div class="login login-box">
  <img class="login login-title" src="/imgs/logo.png">
  <fieldset>
    <%= form_tag '/sessions/create', method: :post do %>
      <div class="login login-field-box">
        <%= text_field_tag 'username', '', class: 'login login-field', placeholder: 'Username' %><br/>
        <%= password_field_tag 'password', '', class: 'login login-field', placeholder: 'Password' %><br/>
      </div>
      <%= submit_tag 'Login', class: 'login login-btn' %>
    <% end %>
  </fieldset>
  <br>
  <%= link_to "Forgot password?", '/users/forgotten', class: 'login link' %><br>
</div>
<div class="login login-box">
  Don't have an account? <%= link_to "Register", register_path, class: 'login link' %>
</div>

app/views/users/edit.html.erb
<%= render 'layouts/userbar', user: @user %>

<div class="user-edit edit-box">
  <h3 class="register-text">Edit Profile</h3>
  <img class="user-edit profile-picture" src="<%= @user.img %>">
  <div>
    <fieldset>
      <%= form_for :user, url: update_profile_path(@user), method: :put do |form| %>
        <div class="register-field-box">
          <div class="user-edit field-row">
            <aside class="user-edit field-text">Username:</aside>
            <%= form.text_field :name, class: 'user-edit field', placeholder: 'Username' %>
          </div>
          <div class="user-edit field-row">
            <aside class="user-edit field-text">Email:</aside>
            <%= form.text_field :email, class: 'user-edit field', placeholder: 'Email' %>
          </div>
          <div class="user-edit field-row">
            <aside class="user-edit field-text">Image:</aside>
            <%= form.text_field :img, size: 40,
                                class: 'user-edit field', placeholder: '/imgs/user.png' %>
          </div>
          <div class="user-edit field-row">
            <aside class="user-edit field-text">New Password:</aside>
            <%= form.password_field :password, size: 20,
                                    class: 'user-edit field', placeholder: 'New Password' %>
          </div>
          <div class="user-edit field-row">
            <aside class="user-edit field-text">Confirm Password:</aside>
            <%= form.password_field :password_confirmation, class: 'user-edit field', placeholder: 'Password confirmation' %>
          </div>
        </div>
        <%= form.submit 'Save', class: 'user-edit save-btn' %>
      <% end %>
    </fieldset>
  </div>
</div>

app/views/users/forgotten.html.erb
<div class="forgotten-box">
  <img src="/imgs/lock.png" class="forgotten lock"><br>
  <div class="forgotten-desc">Trouble Logging In?</div>
  <fieldset>
    <span class="forgotten-expl">Enter your email and we'll send you a link to get back into your account.</span>
    <%= form_tag '/users/recover', method: :post do %>
      <div class="forgotten-field-box">
        <%= text_field_tag 'email', '', class: 'forgotten-field', placeholder: 'Email' %><br/>
      </div>
      <%= submit_tag 'Send Login Link', class: 'forgotten-btn' %>
    <% end %>
  </fieldset>
</div>
<div class="forgotten back-box">
  <%= link_to 'Back to Login', welcome_path, class: 'forgotten back-btn' %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Username</th>
      <th>Password hash</th>
      <th>Salt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.username %></td>
        <td><%= user.password_hash %></td>
        <td><%= user.salt %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="register-box">
  <img class="title-img" src="/imgs/logo.png">
  <div class="register-text">Sign up to see photos and videos from your friends.</div>
  <div>
    <fieldset>
      <%= form_for :user, url: '/users', method: :post do |form| %>
        <div class="register-field-box">
          <%= form.text_field :name, size: 30, class: 'register-field', placeholder: 'Username' %>
          <%= form.text_field :email, size: 40, class: 'register-field', placeholder: 'Email' %>
          <%= form.password_field :password, size: 20, class: 'register-field', placeholder: 'Password' %>
          <%= form.password_field :password_confirmation, size: 20,
                                  class: 'register-field', placeholder: 'Password confirmation' %>
        </div>
        <%= form.submit 'Register', class: 'register-btn' %>
      <% end %>
    </fieldset>
  </div>
  <br>
</div>
<div class="register-box">
  Have an account? <%= link_to "Log in", welcome_path %>
</div>

app/views/users/show.html.erb
<%#= render 'layouts/userbar', user: @auth_user %>

<div class="user-show profile">
  <div class="user-show header"></div>
  <div class="user-show user">
    <img src="<%= @user.img %>" class="user-show profile-picture">
    <h3 class="user-show username"><%= @user.name %> (<%= @user.email %>)</h3>
  </div>
  <div class="user-show statistics">
    <div class="user-show stat-padding"></div>
    <div class="user-show stat-cocktails"><b><%= @user.cocktails.length %></b> cocktails</div>
    <div class="user-show stat-ingredients"><b><%= @user.ingredients.length %></b> ingredients</div>
    <div class="user-show stat-notifications"><b><%= @user.notifications.length %></b> notifications</div>
    <a href="<%= edit_profile_path(@user) %>">
      <div class="user-show edit-btn"><b>Edit</b></div>
    </a>
    <a href="<%= clear_notifs_path(@user) %>">
      <div class="user-show clear-btn"><b>Clear Notifications</b></div>
    </a>
  </div>
  <div class="list-group user-show notif-list">
    <% @user.notifications.each do |notif| %>
      <%= render 'layouts/notif', notif: notif %>
    <% end %>
  </div>
</div>